// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDLis8_5X4hd2pbxF-bNsYI0euy1UW5ORs',
    appId: '1:804030111835:web:aa1dc098f46cabe5495f7e',
    messagingSenderId: '804030111835',
    projectId: 'energylyze',
    authDomain: 'energylyze.firebaseapp.com',
    storageBucket: 'energylyze.firebasestorage.app',
    measurementId: 'G-9ZEVHNS1BN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA2vgCsnb6SrNp5S0RsomWFbOhHluUe9Jg',
    appId: '1:804030111835:android:daf48aa5daaffdfe495f7e',
    messagingSenderId: '804030111835',
    projectId: 'energylyze',
    storageBucket: 'energylyze.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCNDtcwPkGVHJ2eZRLvUV0I0geo1T8gbVE',
    appId: '1:804030111835:ios:9011f7279ab806dd495f7e',
    messagingSenderId: '804030111835',
    projectId: 'energylyze',
    storageBucket: 'energylyze.firebasestorage.app',
    iosBundleId: 'com.example.smartEnergyApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCNDtcwPkGVHJ2eZRLvUV0I0geo1T8gbVE',
    appId: '1:804030111835:ios:9011f7279ab806dd495f7e',
    messagingSenderId: '804030111835',
    projectId: 'energylyze',
    storageBucket: 'energylyze.firebasestorage.app',
    iosBundleId: 'com.example.smartEnergyApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDLis8_5X4hd2pbxF-bNsYI0euy1UW5ORs',
    appId: '1:804030111835:web:889d5d2368cda821495f7e',
    messagingSenderId: '804030111835',
    projectId: 'energylyze',
    authDomain: 'energylyze.firebaseapp.com',
    storageBucket: 'energylyze.firebasestorage.app',
    measurementId: 'G-3GZDSHNQV6',
  );
}
