name: smart_energy_app
description: A new Flutter project.
publish_to: 'none' # Prevents accidental publishing to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.9.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  firebase_core: ^4.2.1
  firebase_auth: ^6.1.2
  cloud_firestore: ^6.0.1
  pdf: ^3.10.4
  printing: ^5.10.0
  dio: ^5.4.0
  http: ^1.2.1
  fl_chart: ^0.68.0 
  provider: ^6.1.1
  image_picker: ^1.0.7
  firebase_storage: ^13.0.4 
  lottie: ^2.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.13.1


flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/animations/
    - assets/images/avatars/

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icons/app_icon.png"
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/icons/app_icon.png"



